# ***** ORIGINAL cloudbuild file - NO LONGER USED ******

# code in dev branch is deployed to dev environment
# master publishes to prod

steps:
# Decrypt to create 2 sets (webservice and files) of identical files with different names
# The correct one will be used based on the env variable set in the respective app.yaml
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.Web/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.Web/appsettings.Development.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.FileProcessor/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.FileProcessor/appsettings.Development.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.Web/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.Web/appsettings.Staging.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.FileProcessor/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.FileProcessor/appsettings.Staging.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.Web/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.Web/appsettings.Production.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - '--ciphertext-file=./PortFreight.FileProcessor/appsettings.$BRANCH_NAME.json.enc'
  - '--plaintext-file=./PortFreight.FileProcessor/appsettings.Production.json'
  - '--location=europe-west1'
  - '--keyring=CLOUDBUILD-SECRETS'
  - '--key=CLOUDBUILD-KEY'
  waitFor: ['-']
#***********

- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  id: 'publish'

- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'test', 'PortFreight.Web.Tests', '--no-build', '-c', 'Release' ]
  waitFor: ['publish']

- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'test', 'PortFreight.Data.Tests', '--no-build', '-c', 'Release' ]
  env:
  - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
  waitFor: ['publish']

- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'test', 'PortFreight.Services.Tests', '--no-build', '-c', 'Release' ]
  waitFor: ['publish']

# Create app.yaml file based on the environment
- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'PortFreight.Web/app.$BRANCH_NAME.yaml', 'PortFreight.Web/bin/Release/netcoreapp2.1/publish/app.yaml' ]
  id: 'web'

- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'PortFreight.FileProcessor/app.$BRANCH_NAME.yaml', 'PortFreight.FileProcessor/bin/Release/netcoreapp2.1/publish/app.yaml' ]
  id: 'files'
#***********


- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy' ]
  dir: './PortFreight.Web/bin/Release/netcoreapp2.1/publish'
  waitFor: ['web']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy' ]
  dir: './PortFreight.FileProcessor/bin/Release/netcoreapp2.1/publish'
  waitFor: ['files']

timeout: 20m
